[2024-06-13T13:27:02.550+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-13T13:27:02.558+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: minio_upload_dag.upload_file_to_minio_0 manual__2024-06-13T13:26:59.308111+00:00 [queued]>
[2024-06-13T13:27:02.563+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: minio_upload_dag.upload_file_to_minio_0 manual__2024-06-13T13:26:59.308111+00:00 [queued]>
[2024-06-13T13:27:02.564+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-13T13:27:02.570+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): upload_file_to_minio_0> on 2024-06-13 13:26:59.308111+00:00
[2024-06-13T13:27:02.577+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'minio_upload_dag', 'upload_file_to_minio_0', 'manual__2024-06-13T13:26:59.308111+00:00', '--job-id', '121', '--raw', '--subdir', 'DAGS_FOLDER/Upload_minio.py', '--cfg-path', '/tmp/tmps09wjiyo']
[2024-06-13T13:27:02.578+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=7521) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-13T13:27:02.579+0000] {standard_task_runner.py:91} INFO - Job 121: Subtask upload_file_to_minio_0
[2024-06-13T13:27:02.579+0000] {standard_task_runner.py:63} INFO - Started process 7523 to run task
[2024-06-13T13:27:02.603+0000] {task_command.py:426} INFO - Running <TaskInstance: minio_upload_dag.upload_file_to_minio_0 manual__2024-06-13T13:26:59.308111+00:00 [running]> on host 5f6ee5e74cc8
[2024-06-13T13:27:02.641+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='minio_upload_dag' AIRFLOW_CTX_TASK_ID='upload_file_to_minio_0' AIRFLOW_CTX_EXECUTION_DATE='2024-06-13T13:26:59.308111+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-13T13:26:59.308111+00:00'
[2024-06-13T13:27:02.643+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-13T13:27:02.656+0000] {base.py:84} INFO - Using connection ID 'minio_s3_connection' for task execution.
[2024-06-13T13:27:02.657+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='minio_s3_connection', conn_type='aws') credentials retrieved from login and password.
[2024-06-13T13:27:03.078+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-13T13:27:03.078+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-13T13:27:03.085+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=minio_upload_dag, task_id=upload_file_to_minio_0, run_id=manual__2024-06-13T13:26:59.308111+00:00, execution_date=20240613T132659, start_date=20240613T132702, end_date=20240613T132703
[2024-06-13T13:27:03.100+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-13T13:27:03.112+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-13T13:27:03.113+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
