[2024-06-12T10:40:45.915+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-12T10:40:45.934+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: minio_upload_dag.upload_file_to_minio manual__2024-06-12T10:40:37.803140+00:00 [queued]>
[2024-06-12T10:40:45.953+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: minio_upload_dag.upload_file_to_minio manual__2024-06-12T10:40:37.803140+00:00 [queued]>
[2024-06-12T10:40:45.957+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-12T10:40:45.989+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): upload_file_to_minio> on 2024-06-12 10:40:37.803140+00:00
[2024-06-12T10:40:46.022+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'minio_upload_dag', 'upload_file_to_minio', 'manual__2024-06-12T10:40:37.803140+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/Upload_minio.py', '--cfg-path', '/tmp/tmpo9828d8y']
[2024-06-12T10:40:46.024+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1890) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-12T10:40:46.026+0000] {standard_task_runner.py:91} INFO - Job 61: Subtask upload_file_to_minio
[2024-06-12T10:40:46.027+0000] {standard_task_runner.py:63} INFO - Started process 1896 to run task
[2024-06-12T10:40:46.117+0000] {task_command.py:426} INFO - Running <TaskInstance: minio_upload_dag.upload_file_to_minio manual__2024-06-12T10:40:37.803140+00:00 [running]> on host 22e84407043d
[2024-06-12T10:40:46.272+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='minio_upload_dag' AIRFLOW_CTX_TASK_ID='upload_file_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2024-06-12T10:40:37.803140+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-12T10:40:37.803140+00:00'
[2024-06-12T10:40:46.274+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-12T10:40:46.410+0000] {base.py:84} INFO - Using connection ID 'minio_s3_connection' for task execution.
[2024-06-12T10:40:46.412+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='minio_s3_connection', conn_type='aws') credentials retrieved from login and password.
[2024-06-12T10:40:51.138+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-12T10:40:51.157+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-12T10:40:51.195+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=minio_upload_dag, task_id=upload_file_to_minio, run_id=manual__2024-06-12T10:40:37.803140+00:00, execution_date=20240612T104037, start_date=20240612T104045, end_date=20240612T104051
[2024-06-12T10:40:51.229+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-12T10:40:51.254+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-12T10:40:51.256+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
